version: '3.8'

services:
  dev:
      container_name: lgt_route_api_dev
      image: nestjs-api-dev:1.0.0
      build:
          context: .
          dockerfile: DOCKERFILE
      command: npm run start:debug
      ports:
          - 8000:9000
      networks:
          - nesjs-network
      volumes:
          - .:/usr/src/app
          - /usr/src/app/node_modules
      restart: unless-stopped
networks:
  nesjs-network: