version: '3.8'

services:
    api:
        container_name: lgt_api_route
        image: sds/lgt-route
        build:
            context: .
            target: development
            dockerfile: Dockerfile
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgresql://doadmin:3o_42Z7FQBI0om2D@location-do-user-9882211-0.b.db.ondigitalocean.com:25060/defaultdb?sslmode=require
            NODE_ENV: development
            PORT: 3000
        # command: npm run start:debug
        ports:
            - 8080:3000
        # networks:
        #     - nesjs-network
        # volumes:
        #     - .:/usr/src/app
        #     - /usr/src/app/node_modules
        # restart: unless-stopped
    postgres:
        image: postgres:latest
        ports:
            - 35000:25060
        # volumes:
        #     - /data/postgres:/data/postgres
        environment:
            POSTGRES_USER: doadmin
            POSTGRES_PASSWORD: 3o_42Z7FQBI0om2D
            POSTGRES_DB: defaultdb
        # networks:
        #     - postgres

    # prod:
    #     container_name: nestjs_api_prod
    #     image: nestjs-api-prod:1.0.0
    #     build:
    #         context: .
    #         target: production
    #         dockerfile: DOCKERFILE
    #     command: npm run start:prod
    #     ports:
    #         - 8000:8000
    #     networks:
    #         - nesjs-network
    #     volumes:
    #         - .:/usr/src/app
    #         - /usr/src/app/node_modules
    #     restart: unless-stopped
# networks:
#     postgres:
#         driver: bridge
#     nesjs-network: